import type {LoaderFunctionArgs} from 'react-router';
import {authenticate} from '../shopify.server';
export async function loader({request}:LoaderFunctionArgs){await authenticate.admin(request);return null}
export default function Privacy(){return <s-page heading="Your store. Your receipts.">
  <s-section heading="What gets recorded"><s-paragraph>Only accepted requests to Bait’s decoy pages: timestamp, catalog or archive, depth, generated records and bytes, recipe version, a random link-chain marker, and a coarse client label. Link chains are not people. Humans, previews outside the app, and retries can look like crawlers.</s-paragraph><s-paragraph>We do not store visitor IP addresses, raw user agents, cookies, request bodies, customer IDs, orders, real products or checkout activity. Shopify connection tokens are stored separately to keep the app installed and authenticated.</s-paragraph></s-section>
  <s-section heading="What happens to it"><s-paragraph>Your private score uses stored totals. The latest 200 trace records per store are retained, with only the last seven days available in reports. Scheduled maintenance removes older traces. The app’s global and store budgets bound recording. Hosting is operated by the app developer.</s-paragraph><s-paragraph>Shared-network reporting and resale are not implemented. Nothing is sent to an enrichment, advertising or AI service. A future contribution program would require a separate, explicit agreement and a permitted Shopify data-use model.</s-paragraph></s-section>
  <s-section heading="Your controls"><s-paragraph>Pause traps at any time, download your score and the latest 20 observations, or uninstall to delete this installation’s session credentials, settings and observations. Disabling the theme embed removes its link; pausing in Bait also closes existing trap URLs. Shopify’s authenticated privacy webhooks are handled.</s-paragraph><s-link href="/app">Back to the score</s-link></s-section>
  <s-section heading="What we cannot see"><s-paragraph>This app cannot inspect every request to your store, intercept /.env probes or measure how much CPU a bot used. Shopify handles its storefront. We only serve our configured app-proxy routes.</s-paragraph></s-section>
</s-page>}
