import {useEffect,useState} from 'react';
import type {ActionFunctionArgs,LoaderFunctionArgs,HeadersFunction} from 'react-router';
import {useFetcher,useLoaderData,useRevalidator} from 'react-router';
import {boundary} from '@shopify/shopify-app-react-router/server';
import {authenticate} from '../shopify.server';
import db from '../db.server';
import {baitStore} from '../bait/store.server';
import {CONSENT_VERSION} from '../bait/contract';
import {generateCatalog,rootDoor} from '../bait/catalog.server';
import {Scoreboard} from '../components/Scoreboard';
const store=baitStore(db);
export async function loader({request}:LoaderFunctionArgs) {
  const {session}=await authenticate.admin(request);
  await store.initialize(session.shop);
  return {score:await store.score(session.shop),shop:session.shop,
    embedUrl:`https://${session.shop}/admin/themes/current/editor?context=apps&activateAppId=${encodeURIComponent(process.env.SHOPIFY_API_KEY||'')}/doors`};
}
export async function action({request}:ActionFunctionArgs) {
  const {session}=await authenticate.admin(request);
  if (Number(request.headers.get('content-length')||0)>4096) return Response.json({error:'That request is too large.'},{status:413});
  const form=await request.formData(), intent=form.get('intent');
  if (intent==='preview') {
    const config=await store.initialize(session.shop);
    return {preview:generateCatalog(session.shop,config.secret,'/apps/bait',rootDoor(),'catalog').body};
  }
  if (intent==='enable') {
    if (form.get('consent')!==CONSENT_VERSION) return {error:'Confirm that you saved the theme embed and agree to record requests to the traps.'};
    await store.enable(session.shop,true);
    return {saved:'The traps are on. Now we wait for a wrong turn.'};
  }
  if (intent==='pause') {await store.enable(session.shop,false);return {saved:'Traps paused. Your recorded score stays put.'};}
  return Response.json({error:'Unknown action.'},{status:400});
}
export default function Index() {
  const {score,embedUrl}=useLoaderData<typeof loader>(), fetcher=useFetcher<typeof action>(), revalidator=useRevalidator();
  const [consent,setConsent]=useState(false),[downloadError,setDownloadError]=useState('');
  useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible'&&revalidator.state==='idle')revalidator.revalidate()},60000);return()=>clearInterval(timer)},[revalidator]);
  const busy=fetcher.state!=='idle';
  async function download(path:string,filename:string) {
    setDownloadError('');
    try {const r=await fetch(path);if(!r.ok||!r.headers.get('content-type')?.includes(path.includes('receipt')?'image/svg+xml':'application/json'))throw Error();
      const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
    } catch {setDownloadError('The download did not finish. Please try again.');}
  }
  return <>
    <Scoreboard score={score} receipt={<button className="bait-receipt-button" onClick={()=>download('/app/receipt','bait-receipt.svg')}>Download receipt ↗</button>}
      controls={<div className="bait-controls">
        <div className="bait-step"><b>1</b><p><s-link href={embedUrl} target="_blank">Enable the catalog door ↗</s-link><br/>Turn on Bait in App embeds, then save your theme. Theme settings control where the door appears.</p></div>
        <div className="bait-step"><b>2</b><p>Turn on the traps here. Only visits to the fake catalog are recorded.</p></div>
        {!score.enabled&&<label className="bait-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I saved the theme embed. Record trap requests for my score: time, door, generated bytes, linked steps and a coarse client label. No shared-network reporting.</label>}
        <s-button variant="primary" disabled={busy||(!score.enabled&&!consent)} onClick={()=>fetcher.submit({intent:score.enabled?'pause':'enable',consent:consent?CONSENT_VERSION:''},{method:'post'})}>{score.enabled?'Pause the traps':'Turn on the traps'}</s-button>
        <div className="bait-control-links"><s-button variant="tertiary" disabled={busy} onClick={()=>fetcher.submit({intent:'preview'},{method:'post'})}>Peek at the bait</s-button><s-button variant="tertiary" onClick={()=>download('/app/export','bait-observations.json')}>Download observations</s-button></div>
        <p className="bait-note">Previewing never changes the score. The embed’s activation is confirmed by you; we don’t request access to read your theme.</p>
        {fetcher.data&&'error' in fetcher.data&&<p className="bait-error" role="alert">{fetcher.data.error}</p>}
        {fetcher.data&&'saved' in fetcher.data&&<p role="status">{fetcher.data.saved}</p>}
        {downloadError&&<p className="bait-error" role="alert">{downloadError}</p>}
      </div>}/>
    {fetcher.data&&'preview' in fetcher.data&&<s-section heading="A peek inside. No points awarded."><s-paragraph>Fictional products, invented prices, and another page. These never enter your Shopify catalog.</s-paragraph><pre className="bait-preview-code">{fetcher.data.preview}</pre></s-section>}
  </>;
}
export const headers:HeadersFunction=args=>({...boundary.headers(args),'Cache-Control':'no-store'});
